
# Fields
ID='Id'
EVENT_ID='eventId'
EVENT_TIME='eventTime'
START_TIME='startTime'
END_TIME='endTime'
EPOCH_START_TIME='epochStartTime'
EPOCH_END_TIME='epochEndTime'
EPOCH_EVENT_TIME='epochEventTime'
SYMBOL='symbol'
BASE_ASSET='baseAsset'
QUOTE_ASSET='quoteAsset'
INTERVAL='interval'
OPEN='open'
CLOSE='close'
HIGH='high'
LOW='low'
VOLUME='volume'
TRADES='trades'
QUOTE_ASSET_VOLUME='quoteAssetVolume'
TAKER_BUY_BASE_ASSET_VOLUME='takerBuyBaseAssetVolume'
TAKER_BUY_QUOTE_ASSET_VOLUME='takerBuyQuoteAssetVolume'
IS_FINAL='isFinal'
ASKS='asks'
BIDS='bids'
TRADE_ID='tradeId'
PRICE='price'
EXCHANGE='exchange'
LEVELS='levels'

ASK_PRICE = 'ask_price'
ASK_QTY = 'ask_quantity'
BID_PRICE = 'bid_price'
BID_QTY = 'bid_quantity'
